version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      nix:
        patterns:
          - 'DeterminateSystems*'
    ignore:
      # They do not support specifying a version in the latest action. Therefore, we need to pin the version for nixpkgs compatibility.
      # See https://github.com/DavidAnson/markdownlint-cli2-action/issues/94 for detail
      - dependency-name: 'DavidAnson/markdownlint-cli2-action'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'gomod'
    directory: '/tool'
    schedule:
      interval: 'monthly'
