version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      nix:
        patterns:
          - 'DeterminateSystems*'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'gomod'
    directory: '/tool'
    schedule:
      interval: 'monthly'
