#!/bin/bash -e

docker run \
    -it \
    -v `pwd`/..:/workspace \
    -u root \
    -e HOME=/root \
    -p 4000:4000 \
    pankona/octopress "cd /workspace && \
      git config --global user.email yosuke.akatsuka@gmail.com && \
      git config --global user.name pankona && \
      /bin/bash"


