baseURL = "https://pankona.github.io"
title = "make clean; make"
theme = "purehugo"
hasCJKLanguage = true
author = "pankona"
Paginate = 5
pygmentscodefences = true
pygmentsstyle = "monokai"

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss"
baseName = "atom"

[params]
  twitterName = "@pankona"
  twitter = ""
  githubName = "pankona"
  google_analytics = "UA-48476608-2"
  image = "https://avatars1.githubusercontent.com/u/6533008?s=460&v=4"

[permalinks]
  posts = "/blog/:year/:month/:day/:filename/"

[blackfriday]
  extensions = ["hardLineBreak"]
