baseURL = "https://pankona.github.io"
title = "make clean; make"
theme = "purehugo"
hasCJKLanguage = true
author = "pankona"
Paginate = 20
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "monokai"

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss"
baseName = "atom"

[params]
  description = "Good poem"
  twitterName = "@pankona"
  twitter = ""
  githubName = "pankona"
  google_analytics = "UA-48476608-2"
  image = "https://avatars1.githubusercontent.com/u/6533008?s=460&v=4"
  paginate = 20

[permalinks]
  posts = "/blog/:year/:month/:day/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
