baseURL = "https://pankona.github.io"
title = "make clean; make"
theme = "purehugo"
hasCJKLanguage = true
author = "pankona"
Paginate = 5
pygmentscodefences = true
pygmentsstyle = "monokai"

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss"
baseName = "atom"

[params]
  description = "Demo site for a hugo theme"
  twitterName = "@gohan_pan_gohan"
  twitter = ""
  githubName = "pankona"
  googleAnalyticsUserID = "UA-48476608-2"

[permalinks]
  posts = "/blog/:year/:month/:day/:filename/"

[blackfriday]
  extensions = ["hardLineBreak"]
