name: generate_site_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - hugo

jobs:
  build:
    if: github.event.sender.login == 'pankona'
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.16'
    - name: clone pankona.github.com
      uses: actions/checkout@v3
      with:
        repository: pankona/pankona.github.com
        path: pankona.github.com
        submodules: 'recursive'
    - name: clone hugo
      uses: actions/checkout@v3
      with:
        repository: gohugoio/hugo
        path: hugo
    - name: install hugo
      run: |
        cd ./hugo
        go install .
    - name: git config
      run: |
        git config --global user.email "yosuke.akatsuka@gmail.com"
        git config --global user.name "pankona"
    - name: generate site and deploy
      run: |
        cd pankona.github.com
        GITHUB_TOKEN=${TOKEN} make deploy
    - name: update submodule
      run: |
        cd pankona.github.com
        git add public && git commit -m "update submodule" && git push origin hugo
