name: generate_pr_from_issue

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

concurrency:
  group: create_pr-from-issue-${{ github.event.issue.number }}
  # Do not set "cancel-in-progress: true" here, just queuing will fit

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        # Needed to specify token for checkout phase, only in push phase is too late
        # https://github.com/orgs/community/discussions/27072#discussioncomment-3254515
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: debug logging for git remotes
      run: git remote -v
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'tool/go.mod'
        cache-dependency-path: 'tool/go.sum'
    - name: install articlegen
      run: |
        cd ./tool/articlegen
        go install .
    - name: install makepr
      run: |
        cd ./tool/makepr
        go install .
    - name: commit
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        title="$ISSUE_TITLE"
        title="${title//\[*\]/}"
        title=`echo $title | xargs`
        title="${title// /-}"
        GITHUB_TOKEN=${TOKEN} articlegen --issue-num=${{ github.event.issue.number }} > content/posts/${title}.md
        git config user.email "yosuke.akatsuka@gmail.com"
        git config user.name "pankona"
        git switch "${title}" || git switch -c "${title}"
        git add content/posts/${title}.md
        git commit -m "add post ${title}"
    - name: push
      env:
        GH_TOKEN: ${{ github.token }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        title="$ISSUE_TITLE"
        title="${title//\[*\]/}"
        title=`echo $title | xargs`
        title="${title// /-}"
        pr_number="$(gh pr list --search "in:title ${title}" --state open --json number --jq 'map(.number)[0]')"
        git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
        git push --force-with-lease
        GITHUB_TOKEN=${TOKEN} makepr --base="main" --head="${title}" --pr_number="${pr_number:=0}" --body="Resolves: ${{ github.event.issue.html_url }}"
