name: Go package

on:
  push:
    paths:
      - 'tool/**'
  pull_request:
    paths:
      - 'tool/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.16'

      - name: Build articlegen
        run: pushd ./tool/articlegen && go build -v ./... && popd

      - name: Build makepr
        run: pushd ./tool/makepr && go build -v ./... && popd

      - name: Build sincelastcommit
        run: pushd ./tool/sincelastcommit && go build -v ./... && popd
