name: CI for Go tools

on:
  push:
    branches:
      - main
    paths:
      - 'tool/**'
  pull_request:
    paths:
      - 'tool/**'

jobs:
  ci-articlegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'tool/go.mod'
          cache-dependency-path: 'tool/go.sum'
      - name: Build
        run: go build -v -C ./tool/articlegen
  ci-makepr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'tool/go.mod'
          cache-dependency-path: 'tool/go.sum'
      - name: Build
        run: go build -v -C ./tool/makepr
  ci-sincelastcommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'tool/go.mod'
          cache-dependency-path: 'tool/go.sum'
      - name: Build
        run: go build -v -C ./tool/makepr

