name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  typo:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.20.3
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go to install yamlfmt
        uses: actions/setup-go@v5
      - name: Install yamlfmt
        run: |
          go install github.com/google/yamlfmt/cmd/yamlfmt@v0.10.0
      - uses: dprint/check@v2.2
        with:
          dprint-version: 0.45.0
