name: notify_long_time_no_see

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    - uses: actions/checkout@v3
    - name: install sincelastcommit
      run: |
        cd ./tool/sincelastcommit
        go install .
        cd ..
    - name: check since last commit
      run: |
        echo "SINCE_LAST_COMMIT=`sincelastcommit`" >> $GITHUB_ENV
    - name: Slack Notification
      if: env.SINCE_LAST_COMMIT >= 7
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: notification
        SLACK_MESSAGE: "最後のブログ更新から ${{ env.SINCE_LAST_COMMIT }} 日過ぎています。"
        SLACK_USERNAME: pankona
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

