name: notify_long_time_no_see

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'tool/sincelastcommit/go.mod'
        cache-dependency-path: 'tool/sincelastcommit/go.sum'
    - name: install sincelastcommit
      run: |
        cd ./tool/sincelastcommit
        go install .
    - name: Debug print for digging sincelastcommit panic
      run: |
        pwd
        git log -- content/posts
    - name: check since last commit
      run: |
        days="$(sincelastcommit)"
        echo "SINCE_LAST_COMMIT=${days}" >> $GITHUB_ENV
    - name: Slack Notification
      if: env.SINCE_LAST_COMMIT >= 7
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: notification
        SLACK_MESSAGE: "最後のブログ更新から ${{ env.SINCE_LAST_COMMIT }} 日過ぎています。"
        SLACK_USERNAME: pankona
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

