name: Typos
on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.16.17
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635761199
          files: |
            .
            .github
            .vscode
