name: Typos
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1.16.0
